In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [ ]:
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [5]:
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400     False        True
1   18  33.770         1   1725.55230      True       False
2   28  33.000         3   4449.46200      True       False
3   33  22.705         0  21984.47061      True       False
4   32  28.880         0   3866.85520      True       False

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent = dataset[['charges']]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.2, random_state=0)

In [9]:
from sklearn.ensemble import AdaBoostRegressor
regr = AdaBoostRegressor(random_state=0, n_estimators=100)
regr.fit(X_train, y_train)

y_pred = regr.predict(X_test)

y_pred

C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([13985.37855442, 13985.37855442, 44892.23363368, 14012.65935331,
       13985.37855442,  7380.2950056 ,  5410.15212949, 13985.37855442,
        7727.40031849,  7727.40031849,  7727.40031849, 13985.37855442,
       11614.71010922,  7727.40031849, 18549.59569903, 13985.37855442,
       14429.04030403,  7727.40031849,  7727.40031849, 40007.44676135,
       24984.53200711, 16467.52439246, 13985.37855442, 24984.53200711,
        5410.15212949,  7727.40031849,  7380.2950056 ,  8782.96435407,
        7727.40031849, 13985.37855442,  8782.96435407, 48307.68410882,
       14429.04030403, 13985.37855442, 18549.59569903,  7727.40031849,
       13985.37855442, 40007.44676135, 43006.40533829,  5410.15212949,
        7380.2950056 ,  7727.40031849, 18549.59569903, 48307.68410882,
       40007.44676135,  5410.15212949, 13985.37855442,  8782.96435407,
        7727.40031849, 13985.37855442,  7727.40031849,  5410.15212949,
       24984.53200711, 48307.68410882, 13985.37855442,  7727.40031849,
        7727.40031849, 13985.37855442, 11614.71010922, 18848.66151973,
        5410.15212949, 48307.68410882, 18848.66151973, 13985.37855442,
       13985.37855442, 13985.37855442, 37183.48329857, 43006.40533829,
        5410.15212949,  8782.96435407, 14429.04030403, 13985.37855442,
       18549.59569903, 14429.04030403, 14012.65935331, 14429.04030403,
       13985.37855442, 13985.37855442, 18549.59569903, 48307.68410882,
       13985.37855442, 43006.40533829,  5410.15212949, 13985.37855442,
       43006.40533829, 18549.59569903,  7727.40031849,  7727.40031849,
       18848.66151973, 40007.44676135,  7727.40031849, 13985.37855442,
        7727.40031849, 13985.37855442,  7727.40031849,  7727.40031849,
       48307.68410882, 40007.44676135,  7727.40031849, 13985.37855442,
        7727.40031849,  7727.40031849,  7727.40031849, 43006.40533829,
       24984.53200711,  7380.2950056 , 13985.37855442,  7727.40031849,
       13985.37855442, 48307.68410882, 16467.52439246,  7727.40031849,
       13985.37855442, 40007.44676135, 48307.68410882,  8782.96435407,
        5410.15212949, 13985.37855442, 18848.66151973, 13985.37855442,
       43006.40533829, 13985.37855442, 14012.65935331,  7727.40031849,
       13985.37855442,  7727.40031849, 24984.53200711, 24984.53200711,
       48307.68410882,  5410.15212949, 13985.37855442,  5410.15212949,
        7727.40031849, 13985.37855442, 28790.40423   , 43006.40533829,
       24984.53200711, 13985.37855442, 24984.53200711,  7727.40031849,
        5410.15212949, 13985.37855442, 13985.37855442, 13985.37855442,
        7727.40031849, 14429.04030403, 18848.66151973,  7727.40031849,
        5410.15212949, 13985.37855442,  7727.40031849, 40007.44676135,
       13985.37855442,  5410.15212949,  5410.15212949,  8782.96435407,
        5410.15212949,  5410.15212949, 13985.37855442, 13985.37855442,
        7727.40031849, 14012.65935331, 14429.04030403, 13985.37855442,
        7380.2950056 ,  7727.40031849, 18549.59569903,  7727.40031849,
        7727.40031849,  5410.15212949,  7727.40031849,  7727.40031849,
       11614.71010922,  7727.40031849,  7727.40031849,  7727.40031849,
        7727.40031849,  8782.96435407, 25653.18245   ,  5410.15212949,
       16467.52439246,  7727.40031849, 13985.37855442,  7727.40031849,
        7727.40031849, 24984.53200711,  5410.15212949,  5410.15212949,
       14429.04030403, 13985.37855442, 44892.23363368,  7727.40031849,
        7727.40031849, 24984.53200711,  7727.40031849,  7727.40031849,
        7727.40031849,  7727.40031849,  7727.40031849,  7727.40031849,
       13985.37855442, 48307.68410882, 16467.52439246, 18549.59569903,
        7727.40031849, 44892.23363368,  7727.40031849, 13985.37855442,
        7727.40031849,  5410.15212949, 13985.37855442, 14429.04030403,
        7727.40031849,  7727.40031849,  8782.96435407,  7727.40031849,
        7727.40031849,  7727.40031849, 18848.66151973,  7727.40031849,
        7727.40031849,  8782.96435407, 13985.37855442,  7727.40031849,
       13985.37855442, 14012.65935331, 16467.52439246, 13985.37855442,
        7727.40031849,  7727.40031849,  5410.15212949, 13985.37855442,
       14429.04030403,  5410.15212949,  7727.40031849,  8782.96435407,
       13985.37855442, 40007.44676135,  7727.40031849, 16467.52439246,
        7727.40031849, 40007.44676135,  8782.96435407,  9111.08199468,
       11614.71010922, 13985.37855442,  5410.15212949, 11614.71010922,
        5410.15212949,  8782.96435407, 18549.59569903, 48307.68410882,
        7727.40031849,  7727.40031849,  5410.15212949,  5410.15212949,
       13985.37855442,  5410.15212949,  7727.40031849,  7727.40031849,
       13985.37855442, 24984.53200711, 48307.68410882, 18848.66151973,
        8782.96435407, 13985.37855442, 40007.44676135, 13985.37855442])

In [10]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

r2_score = r2_score(y_test, y_pred)

In [11]:
r2_score

0.8648762914305494